DRAFT - feature-extraction /  feature-matching.mdx
johko/computer-vision-course pull request #106
Opened 2023-12-08 22:23 UTC by kfahn22

First draft of feature-matching.mdx.  Here are the images.  I have updated the images and made a pull request to add them to the assets repo.

![SIFT](https://github.com/johko/computer-vision-course/assets/65121394/1f63d776-a0b3-4a71-8bc0-6d3379cacc15)
![FLANN](https://github.com/johko/computer-vision-course/assets/65121394/4e9aa92d-b981-4b4f-bdd6-51db36ae010c)
![LoFTR](https://github.com/johko/computer-vision-course/assets/65121394/b07e4337-e019-4db6-b832-bb12ff79c934)

2023-12-09 04:49 UTC, merveenoyan reviewed
Content-wise I loved the puzzle example and how you explained all the algorithms, I loved the initial story telling, I just did nit-picking on formatting, I learnt a lot, thank you 🥹 🤗

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +How can we match detected features from image-to-image? Feature matching involves comparing key features or characteristics in different
```suggestion
How can we match detected features from one image to another? Feature matching involves comparing key features or characteristics in different
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +images to find similarities. For example, you might want to match features between two images to identify objects or recognize patterns.
this section continues in new line

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +you decide to check every single piece, one by one, until you find the right one. This straightforward method is like a brute force search.
```suggestion
you decide to check every piece, one by one until you find the right one. This straightforward method is a brute-force search.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +OK, now that we have an intuitive idea of how brute force matches are found, let's dive into the algorithms.
```suggestion
Now that we have an intuitive idea of how brute-force matches are found, let's dive into the algorithms.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +_First install and load libraries_
```suggestion
First install and import the libraries.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +_Brute Force with SIFT_
```suggestion
**Brute Force with SIFT**
```
maybe you could define what SIFT does here

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +1.  Load Images
```suggestion
We will now load our images to have their features matched.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +2. Initiate SIFT detector
```suggestion
Initialize SIFT detector.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +3. Find the keypoints and descriptors with SIFT
```suggestion
Find the keypoints and descriptors with SIFT.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +4. Find matches using k nearest neighbors
```suggestion
Find matches using k-nearest neighbors.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +5. Apply ratio test to threshold the best matches
```suggestion
Apply ratio test to threshold the best matches.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +5. Draw the matches
```suggestion
Draw the matches.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +_Brute Force with ORB (binary) descriptors_
```suggestion
**Brute Force with ORB (binary) descriptors**
```
You can also have them level three headers (###)

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +1.  Load images
```suggestion
Load images.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +2.  Intialize the ORB descriptor:
```suggestion
Initialize the ORB descriptor.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +4. Find key points and descriptors:
```suggestion
Find key points and descriptors.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +3.  Because ORB is a binary descriptor, we ind matches using Hamming Distance, which is a measure of the difference between
```suggestion
Because ORB is a binary descriptor, we find matches using Hamming Distance, which is a measure of the difference between
```
Maybe you could give a link to hamming distance

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +4.  Find the matches
```suggestion
Find the matches.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +5. Sort them in the order of their distance.
```suggestion
Sort them in the order of their distance.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +6. Draw first n matches.
```suggestion
Draw the first n matches.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +_First we create a dictionary to specify the algorithm we will use:_
```suggestion
First we create a dictionary to specify the algorithm we will use.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +1.  Load images
```suggestion
Load images.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +````
```suggestion
```
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +2. Initiate SIFT detector
```suggestion
Initialize SIFT detector.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +3. Find the keypoints and descriptors with SIFT
```suggestion
Find the keypoints and descriptors with SIFT.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +3. Define the FLANN parameters. Trees is the numbers of bins you want.
```suggestion
Define the FLANN parameters. Trees is the numbers of bins you want.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +4. We will only draw only good matches, so create a mask
```suggestion
We will only draw only good matches, so create a mask.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +5. We perform a ratio test to determine good matches
```suggestion
We perform a ratio test to determine good matches.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +6. Now we visualize the matches
```suggestion
Now we visualize the matches.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +1.  Import the libraries
```suggestion
Import the libraries.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +2. Load and resize the images
```suggestion
Load and resize the images.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +3.  Indicate whether the image is an "indoor" or "outdoor" image
```suggestion
Indicate whether the image is an "indoor" or "outdoor" image.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +4.  LoFTR only works on grayscale images, so convert to grayscale
```suggestion
LoFTR only works on grayscale images, so convert to grayscale.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +5. Perform Inference
```suggestion
Perform inference.
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +6. We can clean up the correspondences using Random Sample Consensus (RANSAC), which help
```suggestion
We can clean up the correspondences using Random Sample Consensus (RANSAC), which help
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +7. Finally, we visualize the matches
```suggestion
Finally, we visualize the matches
```

2023-12-09 04:49 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +[FLANN Github](https://github.com/flann-lib/flann)
Maybe have them as a list with - for readability?

2023-12-09 18:52 UTC, kfahn22 commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +_Brute Force with SIFT_
I didn't provide a discussion  b/c it is covered in feature-description.md.  Do you think I should add something here as well?

2023-12-09 19:12 UTC, kfahn22 commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +images to find similarities. For example, you might want to match features between two images to identify objects or recognize patterns.
I have rewritten this and hopefully fixed the line-break issue.

2023-12-10 14:29 UTC, kfahn22 commented
I think I have made all of the requested changes.  Please let me know if I have missed anything or need to make additional changes.

2023-12-11 13:50 UTC, merveenoyan reviewed
Thanks a lot for iterating on this, if you can remove newlines and reduce header 3 to bold text we can merge 😊 
<img width="588" alt="Screenshot 2023-12-11 at 14 47 05" src="https://github.com/johko/computer-vision-course/assets/53175384/1f005560-695a-4544-94c5-ee44869ac1ee">

2023-12-11 13:50 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### Intialize the ORB descriptor:
```suggestion
### Initialize the ORB descriptor:
```

2023-12-11 13:50 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### We will now load our images to have their features matched.
This will appear smaller than **Brute Force with SIFT** which is just a bold text, maybe for each step above code snippets you can turn into bold instead of making each a header

2023-12-11 13:50 UTC, merveenoyan commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +two strings of equal length
Because of newline this is not formatted

2023-12-11 19:19 UTC, MKhalusova reviewed
Thank you for writing this, a nice and cohesive page with a consistent example. Great work! Left a few nits.

2023-12-11 19:19 UTC, MKhalusova commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### Initiatize SIFT detector
Do the learners know at this point what a SIFT detector does/is?

2023-12-11 19:19 UTC, MKhalusova commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### Find the keypoints and descriptors with SIFT
Again, are the learners familiar with what the keypoints and descriptors are?

2023-12-11 19:19 UTC, MKhalusova commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### Find key points and descriptors:
Earlier, it was spelled "keypoints", here it is "key points". Which one is correct? Also, a colon at the end of a header is unnecessary.

2023-12-11 19:19 UTC, MKhalusova commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### Because ORB is a binary descriptor, we find matches using [Hamming Distance](https://www.geeksforgeeks.org/hamming-distance-two-strings/), which is a measure of the difference between
This probably shouldn't be a header, but a regular paragraph.

2023-12-11 19:19 UTC, MKhalusova commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### Sort them in the order of their distance.
```suggestion
### Sort them in the order of their distance
```

2023-12-11 19:19 UTC, MKhalusova commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### Draw first n matches.
```suggestion
### Draw first n matches
```

2023-12-11 19:19 UTC, MKhalusova commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### First we create a dictionary to specify the algorithm we will use.
```suggestion
### First we create a dictionary to specify the algorithm we will use
```

2023-12-11 19:19 UTC, MKhalusova commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +_We also create a dictionary to specify the maximum leafs to visit:_
```suggestion
We also create a dictionary to specify the maximum leafs to visit:
```

2023-12-11 19:19 UTC, MKhalusova commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### Find the keypoints and descriptors with SIFT.
```suggestion
### Find the keypoints and descriptors with SIFT
```

2023-12-11 19:19 UTC, MKhalusova commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### We will only draw only good matches, so create a mask
```suggestion
### We will only draw good matches, so create a mask
```

2023-12-11 20:09 UTC, kfahn22 commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### Find the keypoints and descriptors with SIFT
feature description.mdx discusses the SIFT algorithm and keypoints/descriptors -- let me know if I need to add more detail here

2023-12-11 20:14 UTC, kfahn22 commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +### Initiatize SIFT detector
This should be covered in previous chapter (feature description)

2023-12-11 20:37 UTC, kfahn22 commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +two strings of equal length
I think  I have removed the newlines

2023-12-12 13:03 UTC, merveenoyan commented
@kfahn22 if you could fix newlines in the document we can merge this

2023-12-12 21:52 UTC, kfahn22 commented
@merveenoyan I have tried to fix newlines.

2023-12-13 13:59 UTC, merveenoyan commented
@kfahn22 we need an approval, I'll ping bunch of people from discord for this :)

2023-12-13 15:29 UTC, ratan approved these changes
Look good.
Thanks for nice explanation

2023-12-13 15:40 UTC, MKhalusova approved these changes
LGTM, but maybe we should add links to the images before merging? So that we don't forget to do that later.

2023-12-14 08:08 UTC, mmhamdy requested changes

2023-12-14 08:08 UTC, mmhamdy commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +**Brute Force with SIFT**
Amazing tutorial! I only have one *small* suggestion. In my opinion, using a heading (e.g. Heading 3 in this case) instead of bold for the algorithms would make it much easier for navigation.

2023-12-14 08:30 UTC, mmhamdy commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +**Brute Force with SIFT**
After checking the history, I found that you were using heading 3 for the steps and @merveenoyan suggested using bold instead. For this to not feel redundant😅, let me be a little more clear. I'm just suggesting using the heading for the algorithms and not the steps. Again, this is just a suggestion, your writing is truly wonderful!

2023-12-14 12:36 UTC, johko approved these changes
Two small grammar/typo things, but I'll already leave my approval.

2023-12-14 12:36 UTC, johko commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +**Initiatize SIFT detector**
```suggestion
**Initialize SIFT detector**
```

2023-12-14 12:36 UTC, johko commented on chapters/en/Unit 1 - Fundamentals/feature-extraction/feature-matching.mdx
> +which is a measure of the difference between two strings of equal length
```suggestion
which is a measure of the difference between two strings of equal length.
```

2023-12-14 17:44 UTC, kfahn22 commented
I have edit styling, fixed typos, and added links.

2023-12-14 20:50 UTC, mmhamdy approved these changes

2023-12-14 20:51 UTC, merged