Update the Transfer Learning for NN Architecture part
johko/computer-vision-course pull request #13
Opened 2023-10-05 17:16 UTC by sitloboi2012

- Update `README.md` and `Fine-tune-LayoutLM-For-Document-Image-Classification.ipynb` files for `2 Neural Network Architectures / 2.3 Multi-Modal Model / 2.3.3 Transfer Learning`

2023-10-05 17:54 UTC, chiho-5 commented
Hi , 
Great work but I think that more explanation is required. I would suggest introducing what type of model LayoutLM is, if it's associated with any research paper or not, tasks most suitable for LayoutLM etc. You can as well collaborate with people. Anticipating the changes soon🚀

2023-10-05 17:59 UTC, sitloboi2012 commented
Cool, thank you for your feedback, I will add on more information related to the model itself, any other relevants info that is helpful for other user

2023-10-05 18:45 UTC, sitloboi2012 commented
hi @chiho-5 , can you help me check the PR again? I made some updates related to adding information about the model background, related information like research paper, model card hub, huggingface docs, GitHub link and an introduction about the document image classification task as well

2023-10-05 19:29 UTC, chiho-5 commented
> hi @chiho-5 , can you help me check the PR again? I made some updates related to adding information about the model background, related information like research paper, model card hub, huggingface docs, GitHub link and an introduction about the document image classification task as well

Okay. Give me some time to go through all of it. I've also requested for extra reviews. I'd give you my feedback and suggestions soon

2023-10-05 19:49 UTC, chiho-5 commented
Hi,
Thanks for adding more information. It seems like some information is repeated in two different MD files. Can you resolve that please. Generic information should be in the ReadMe and then model specific information should be in the introduction file inside the folder.

2023-10-05 20:22 UTC, johko requested changes
Thanks for the amazing (and very quick) effort! I mainly did a bunch of grammar corrections and added some other suggestions.
I also have to review the notebook separately (as it is hell in the standard github view ;) )

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/Document Image Classification/Introduction.md
> +This folder contains the implementation, training, fine-tuning and inference using different multimodal models. Refer to the list below for more information.
I appreciate the eagerness, but lets try to keep it at fine-tuning and inference here to not overload it.
```suggestion
This folder contains the fine-tuning and inference using different multimodal models. Refer to the list below for more information.
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/Document Image Classification/Introduction.md
> +- LayoutLMv3: _TBA_
I think having example code for one LayoutLM version here is enough. I would probably go for the latest, so v3 and maybe just mention that the other versions exist and give a link somewhere in the notebook.

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> +In this directory, you can find multiple notebooks that introduce you how to fine-tuning Multimodal models to downstream task like:
```suggestion
In this directory, you can find multiple notebooks that introduce how to fine-tune Multimodal models to downstream task like:
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> +We use different type of Multimodal Models ranging from:
```suggestion
We use different types of Multimodal Models ranging from:
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> + - Visual Document Question Answering
Could we make that more general and call it Visual Question Answering? One of the examples in there can of course be Document specific

```suggestion
 - Visual Question Answering 
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> +This would include also the setup for training, fine-tuning and inferencing at the end. Feel free to use as sources for your project.
Again I would cut the training part, to make it a bit lighter. In the end fine-tuning is a kind of training I guess, so we don't need to mention that explicitly
```suggestion
This includes also the setup for fine-tuning and inferencing at the end. Feel free to use them as sources for your project.
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> +For Multimodal model related to Text and Image, feel free to start with this [paper](https://arxiv.org/abs/2111.08609).
```suggestion
For Multimodal models related to Text and Image, feel free to start with this [overview paper](https://arxiv.org/abs/2111.08609).
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/README.md
> +Multimodal is a multi-disciplinary research field where we aim to develop and create model that able to solve multiple aspects at the same time in terms but not limited to text, image, video, etc.
```suggestion
Multimodal is a multi-disciplinary research field where we aim to develop and create models that are able to solve multiple aspects at the same time in terms but not limited to text, image, video, etc.
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/README.md
> +Example that could be model work with Image and Text like LayoutLM, CLIP, DETR, etc.
```suggestion
Example of models that work with image and text data are LayoutLM, CLIP, DETR, etc.
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> +The model can fine-tune downstream various tasks:
```suggestion
The model can be fine-tuned on various downstream tasks:
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> +LayoutLM is a multimodal model that is develop by the [Microsoft Document AI](https://www.microsoft.com/en-us/research/project/document-ai/overview/) team where they most focusing on develop techniqu
```suggestion
LayoutLM is a multimodal model that was developed by the [Microsoft Document AI](https://www.microsoft.com/en-us/research/project/document-ai/overview/) team where they are focusing on develop techniques and models to solve the problem of understanding, extracting and analysing complex document such as PDF, Word Document, HTML, XML, etc.
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> +The backbone of the model is Transformers architecture with Text Embedding to handle text input and Image Embedding to handle image input. Depend on the version, the embedding techniques and pre-trai
```suggestion
The backbone of the model is the Transformers architecture, which uses Text Embeddings to handle text input and Image Embedding to handle image input. Depending on the version, the embedding techniques and pre-trained tasks might be slightly different.
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> +For more paper related to LayoutLM family:
```suggestion
For more papers related to LayoutLM family:
```

2023-10-05 20:22 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> +# Model Introduction
I like the idea of the model introduction, but maybe this is better located in the folder of the tasks that these models are tackling (like Document Classification for LayoutLM) or in the corresponding notebook, so the README here does not get too inflated.

2023-10-05 20:35 UTC, chiho-5 requested changes
@johko made some good suggestions about not overloading the ReadMe. The model intro is okay but all the references are not necessary. I think just citing the latest version is okay plus updating the code to make use of the latest version if it doesn't. I haven't taken time to go through the codes yet.

2023-10-06 02:46 UTC, sitloboi2012 commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/Document Image Classification/Introduction.md
> +- LayoutLMv3: _TBA_
cool, thank you for everyone feedback, I will look into that today and update the PR again. Cheers everyone

2023-10-06 02:46 UTC, sitloboi2012 commented
cool, thank you everyone for the feedback, I will review it today and make change based on the feedback, will ping you guy when the update is done, pretty good start

2023-10-06 04:02 UTC, sitloboi2012 commented
hi @chiho-5 , @johko and @merveenoyan , i made some updates based on the team feedback, this includes: changing the notebook model from LayoutLMv1 to v3, updating the Introduction.md and the README.md to make it clearer, removing repetition and adjust some links to reduce the size a bit.

Have a look through to see if I still missed anything based on your guy's feedback, sorry if I made any grammatical errors or stuff 🤣

2023-10-06 12:18 UTC, sitloboi2012 reviewed
just a typo error for the word "Video"

2023-10-06 12:18 UTC, sitloboi2012 commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> + - Text-to-Vide
Typo error: Text-to-Video

2023-10-06 13:37 UTC, sitloboi2012 reviewed
Change reviewed

2023-10-10 12:38 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/README.md
> +We have also included sources on state-of-the-art (SOTA) and current developments in multimodal models, providing you with the most up-to-date information in this field..
This sentence is true for the moment, but knowing the field things change rapidly and in half a year it might already be new SOTA models.
I would vouch for making the claim a bit less "up-to-date"

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<p>maybe add a comment at the top that this cell is just for creating the requirements.txt file with the needed libraries.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<p>"We<strong>'re </strong>going to use ..." </p><p>"...you can also use <strong>the</strong> dataset..."</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<p>I would add some more comments in this block what is actually happening in the lines (not everything, but most important parts) as they look a bit confusing (especially for people newbies)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<p>"... with pretrained <strong>checkpoints</strong> and <strong>encode the dataset</strong>" (just a suggestion, but something like this)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<p>"Double check the data before feed<strong>ing it</strong> to the model"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<p>"Model Initialization" or "Initialize Model"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='28'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<p>a pretty bunch of metrics, have you checked if you can also load them with the evaluate (<a href="https://huggingface.co/docs/evaluate/index" target="_blank">https://huggingface.co/docs/evaluate/index</a>) library? just to stay more in the HF ecosystem, else this also works</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='31'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #6.          return train_dataloader # please change this to your evaluate dataset
</pre><p>What do people have to do to get the eval dataset? I think it would be helpful to have instructions for it (maybe I also just missed it)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='37'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #7.        eval_dataset=train_encoded_dataset, # please change this to your evaluate dataset
</pre><p>same eval dataset thing as above</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='38'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #1.    predictions, labels, metrics = trainer.predict(train_encoded_dataset)
</pre><p>here you would probably want to use a separate split of the dataset, just to not get people used to evaluating on the train set.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='43'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<p>"The model<strong>'s</strong> current performance <strong>metrics</strong> are: ...."</p><p>"... and false positives <strong><s>label</s></strong> globally, ..."</p><p>"But for each label specifically, there <strong>is</strong> still room for improvement"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='45'/>

2023-10-10 13:02 UTC, johko commented on course/2 Neural Network Architectures/2.3 Multi-Modal Models/2.3.3 Transfer Learning/LayoutLMv3/Fine_tune_LayoutLMv3_For_Document_Image_Classification_RVL_CDIP.ipynb
> +{
<p>What do you mean by that? Or maybe you can mention what Rays does to help (and give a link)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/johko/computer-vision-course/pull/13/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='46'/>

2023-10-10 14:54 UTC, merveenoyan requested changes
I found this PR very overwhelming by means of additions. In the contribution guideline, it's encouraged to make atomic PRs and not add everything at once. Moreover, please stick to style of [Hugging Face course](https://huggingface.co/learn/nlp-course/chapter1/1), and avoid mentioning directories (and also have the structure like in [toctree of transformers](https://github.com/huggingface/course/blob/main/chapters/en/_toctree.yml) course. Also see [here](https://github.com/huggingface/course/tree/main/chapters/en) for how it's shaped.

2023-10-10 15:04 UTC, sitloboi2012 commented
hey team, Im going to close this PR as it's quite big and try to break it down a bit. I will open a PR that its smaller and take in consideration @merveenoyan, @johko and @chiho-5 comment to make it better

2023-10-10 15:04 UTC, closed without merging