Add Variational Autoencoder and GANs
johko/computer-vision-course pull request #131
Opened 2023-12-17 12:49 UTC by sarthak247

Add Variational Autoencoder and GANs part for Unit 12 - Generative Models

2023-12-17 15:22 UTC, ariG23498 requested changes
This is a very thorough write up for GANs. I am yet to review the VAEs.

2023-12-17 15:22 UTC, ariG23498 commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +Generative Adversarial Networks (GANs) are a class of deep learning models introduced by [Ian Goodfellow](https://scholar.google.ca/citations?user=iYN86KEAAAAJ&hl=en) and his colleagues in 2014. The
Sometimes the `discriminator` is refered to as the `critic`. I have always liked this term better as this directly comes from the analogy of a painter (generator) and an art critic (discriminator). This analogy was part of the [GAN course from DeepLearning.ai](https://www.deeplearning.ai/courses/generative-adversarial-networks-gans-specialization/).

This is not a suggestion. Might be interesting to pursue this analogy in the introductory paragraph. Really drives the intuition home.

2023-12-17 15:22 UTC, ariG23498 commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +        * **Weaknesses:** May not be as effective as GANs for tasks that require high-quality image generation.
I would always cite different papers to prove the pointers mentioned. If not papers, reports of experiments conducted.

2023-12-17 15:22 UTC, ariG23498 commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +|Applications|Image Generation, Super-resolution, image-to-image translation|Image Denoising, Anamoly Detection, Signal Analysis|
This is so neat! A summarizer of all the pointers is a very thoughtful.

2023-12-17 15:22 UTC, ariG23498 commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +## Section 2.3 Training GANs
[Slide 12: Using Math to Communicate](https://docs.google.com/presentation/d/e/2PACX-1vRau7IXhvdKKOZQt3hujyw5dNltExsmxfHTMbHTpwUXK4mst-lXMPkLQL8MRNsVVONWRgBdTf5W3k4c/pub?start=false&loop=false&delayms=3000&slide=id.g157b6906e85_0_25)
[Slide 13: The Samplings](https://docs.google.com/presentation/d/e/2PACX-1vRau7IXhvdKKOZQt3hujyw5dNltExsmxfHTMbHTpwUXK4mst-lXMPkLQL8MRNsVVONWRgBdTf5W3k4c/pub?start=false&loop=false&delayms=3000&slide=id.g157b6906e85_0_38)
[Slide 14: Discriminator](https://docs.google.com/presentation/d/e/2PACX-1vRau7IXhvdKKOZQt3hujyw5dNltExsmxfHTMbHTpwUXK4mst-lXMPkLQL8MRNsVVONWRgBdTf5W3k4c/pub?start=false&loop=false&delayms=3000&slide=id.g157b6906e85_0_50)
[Slide 15: Generator](https://docs.google.com/presentation/d/e/2PACX-1vRau7IXhvdKKOZQt3hujyw5dNltExsmxfHTMbHTpwUXK4mst-lXMPkLQL8MRNsVVONWRgBdTf5W3k4c/pub?start=false&loop=false&delayms=3000&slide=id.g157bb6d6115_0_2)
[Slide 16: Revisited](https://docs.google.com/presentation/d/e/2PACX-1vRau7IXhvdKKOZQt3hujyw5dNltExsmxfHTMbHTpwUXK4mst-lXMPkLQL8MRNsVVONWRgBdTf5W3k4c/pub?start=false&loop=false&delayms=3000&slide=id.g157bb6d6115_0_19)

These might help you build a better intuition about the min max game.

A [desmos](https://www.desmos.com/calculator/nw6m38xtij) demo for the mathametical equation also helps here.

2023-12-18 15:58 UTC, merveenoyan reviewed
I only left formatting nits, thank you!

2023-12-19 00:42 UTC, sarthak247 commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +        * **Weaknesses:** May not be as effective as GANs for tasks that require high-quality image generation.
I got these points after some Google search and from some medium posts. I don't know of any papers which directly reference a comparison like this between GANs and VAEs so if you know of any paper do let me know and I will add it. Cheers :v:

2023-12-19 00:51 UTC, sarthak247 commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +        * **Weaknesses:** May not be as effective as GANs for tasks that require high-quality image generation.
I think this should work. Although I'm not sure about the sources
* [What are the fundamental differences between VAE and GAN for image generation?](https://ai.stackexchange.com/questions/25601/what-are-the-fundamental-differences-between-vae-and-gan-for-image-generation)
* [Issues with GAN and VAE models](https://stats.stackexchange.com/questions/541775/issues-with-gan-and-vae-models)
* [VAE Vs. GAN For Image Generation](https://www.baeldung.com/cs/vae-vs-gan-image-generation)
* [Diffusion Models vs. GANs vs. VAEs: Comparison of Deep Generative Models](https://towardsai.net/p/machine-learning/diffusion-models-vs-gans-vs-vaes-comparison-of-deep-generative-models)

2023-12-19 01:08 UTC, sarthak247 commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +Generative Adversarial Networks (GANs) are a class of deep learning models introduced by [Ian Goodfellow](https://scholar.google.ca/citations?user=iYN86KEAAAAJ&hl=en) and his colleagues in 2014. The
Added

2023-12-19 04:56 UTC, sarthak247 commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +## Section 2.1 Introduction to GANs
I've resolved these grammatical errors. However, if there are any remaining please do let me know. Cheers :v:

2023-12-20 12:59 UTC, merveenoyan reviewed
This is very close to merger! Just left formatting and typo corrections 🤗 
also @ariG23498 can you leave another review? @sarthak247 has iterated on the content and we'll have to merge next

2023-12-20 12:59 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +## Section 2.2 GANs vs VAEs
```suggestion
## GANs vs VAEs
```
No need for numbering

2023-12-20 12:59 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/variational_autoencoders.mdx
> +## Variational Autoencoders (VAEs) Overview:
```suggestion
## Variational Autoencoders (VAEs) Overview
```

2023-12-20 12:59 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/variational_autoencoders.mdx
> +![Variational Autoencoder - Lilian Weng Blog](https://lilianweng.github.io/posts/2018-08-12-vae/vae-gaussian.png)
You can add the images to hf-vision/course-assets and give a reference so even if the image is reviewed from the source it won't be removed from here

2023-12-20 12:59 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +        * **Strengths:** Widely used for tasks like image denoising and anamoly detection.
```suggestion
        * **Strengths:** Widely used for tasks like image denoising and anomaly detection.
```

2023-12-20 12:59 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +Ultimately, the best choice depends on one's specific needs and priorities. If one need high-quality images for tasks like generating realistic faces or landscapes, then a GAN might be the better cho
```suggestion
Ultimately, the best choice depends on one's specific needs and priorities. If one needs high-quality images for tasks like generating realistic faces or landscapes, then a GAN might be the better choice. However, if one needs a model that is easier to train and more stable, then a VAE might be a better option.
```

2023-12-20 12:59 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +A common analogy which can be found online is that of an art forger/painter (the geneator) which tries to forge paintings and an art investigator/critic (the discriminator) which triest to detect imi
```suggestion
A common analogy that can be found online is that of an art forger/painter (the generator) which tries to forge paintings and an art investigator/critic (the discriminator) who tries to detect imitations.
```

2023-12-20 12:59 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +GANs and VAEs are both popular generative models in the field of machine learning, but they have different strengths and weaknesses. Whether one is "better" than the other depends on the specific tas
```suggestion
GANs and VAEs are both popular generative models in machine learning, but they have different strengths and weaknesses. Whether one is "better" depends on the specific task and requirements. Here's a breakdown of their strengths and weaknesses.
```

2023-12-22 12:24 UTC, ariG23498 approved these changes
Looks good to me!

Love how crisp and to the point this is. 🤗

2024-01-05 01:00 UTC, sarthak247 commented on chapters/en/Unit 5 - Generative Models/gans.mdx
> +        * **Strengths:** Generate higher quality images, especially for complex data with sharp details and realistic textures.
I've addressed the other issues but I believe removing the indentations might impact the structure of the content. Please let me know whether it should still be removed or kept.

2024-01-05 01:00 UTC, sarthak247 commented on chapters/en/Unit 5 - Generative Models/variational_autoencoders.mdx
> +![Variational Autoencoder - Lilian Weng Blog](https://lilianweng.github.io/posts/2018-08-12-vae/vae-gaussian.png)
I'll update them as soon as it gets merged to hf-vision/course-assets

2024-01-05 01:54 UTC, sarthak247 commented
I've made the requested changes :v:

2024-01-05 16:19 UTC, merveenoyan commented
@sarthak247 can you check out rest of the chapters and if it doesn't exist, maybe add a very minimal PyTorch implementation of a GAN and a VAE?

2024-01-06 14:15 UTC, merveenoyan approved these changes
@sarthak247 I'll merge this one, you can raise another PR for the implementation if it's o 🤗 thanks a lot!

2024-01-06 14:15 UTC, merged