Unit 12. Generative models - Practical issues
johko/computer-vision-course pull request #136
Opened 2023-12-17 16:19 UTC by hwaseem04

Brief idea into the Ethical Issues associated with generative contents.

2023-12-18 05:41 UTC, ricard-inho reviewed
I think something to consider if there's time is this [article](https://www.technologyreview.com/2023/10/23/1082189/data-poisoning-artists-fight-generative-ai/). It comes from the following [text](https://arxiv.org/abs/2310.13828). It talks about scraping copyright data for generative models.

2023-12-18 05:41 UTC, ricard-inho commented on chapters/en/Unit 5 - Generative Models/PRACTICAL APPLICATIONS & CHALLENGES/Ethical Issues.mdx
> +- **Advanced detection and mitigation techniques**: Researchers will ideally develop more advanced techniques for detecting and mitigating the harms associated with AI-edited images. But is like a ca
```suggestion
- **Advanced detection and mitigation techniques**: Researchers will ideally develop more advanced techniques for detecting and mitigating the harms associated with AI-edited images. But is like a cat and dog game, where one group develops sophisticated realistic AI images generating algorithms whereas another group develops methods to identify them
```

2023-12-18 17:21 UTC, merveenoyan reviewed
Thanks a lot for this section! Can you make the file names consistent, i.e.  chapters/en/Unit 5 - Generative Models/Practical Applications and Challenges/Ethical Issues.mdx

2023-12-18 17:21 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/PRACTICAL APPLICATIONS & CHALLENGES/Ethical Issues.mdx
> +
```suggestion
```

2023-12-18 17:21 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/PRACTICAL APPLICATIONS & CHALLENGES/Ethical Issues.mdx
> +    - Impact of such AI images/videos on Society
```suggestion
- Impact of such AI images/videos on society
```
You can remove the indentations and capitals mid-sentence

2023-12-18 17:21 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/PRACTICAL APPLICATIONS & CHALLENGES/Ethical Issues.mdx
> +- **Undermine trust in media**: Deepfakes, convincingly manipulated videos, can spread misinformation and erode public trust in news and online content.
```suggestion
- **Undermine trust in media:** Deepfakes, convincingly manipulated videos, can spread misinformation and erode public trust in news and online content.
```

2023-12-18 17:21 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/PRACTICAL APPLICATIONS & CHALLENGES/Ethical Issues.mdx
> +- **Advanced detection and mitigation techniques**: Researchers will ideally develop more advanced techniques for detecting and mitigating the harms associated with AI-edited images. But is like a ca
```suggestion
- **Advanced detection and mitigation techniques**: Researchers will ideally develop more advanced techniques for detecting and mitigating the harms associated with AI-edited images. But it is like a cat and dog game: where one group develops sophisticated, realistic image generation algorithms, whereas another group develops methods to identify them.
```

2023-12-18 17:21 UTC, merveenoyan commented on chapters/en/Unit 5 - Generative Models/PRACTICAL APPLICATIONS & CHALLENGES/Ethical Issues.mdx
> +- **Public awareness and education**: Public awareness campaigns and educational initiatives will be crucial in promoting responsible use of AI-edited images and combating the spread of misinformatio
```suggestion
- **Public awareness and education:** Public awareness campaigns and educational initiatives will be crucial in promoting responsible use of AI-edited images and combating the spread of misinformation.
```

2023-12-20 22:59 UTC, WilliamBonvini reviewed
Why there are all those empty README.md files? Maybe they don't cause any problem, but I don't think they are supposed to be there, right?

2023-12-26 20:26 UTC, johko commented on chapters/en/Unit 5 - Generative Models/PRACTICAL APPLICATIONS & CHALLENGES/Ethical Issues.mdx
> +This is a rapidly evolving field, and it is crucial to stay informed about the latest developments.
Do you have any sources for the ethical part people can follow - websites, social media accounts? Maybe would be nice if you know any. But if not, that is okay as well :)

2023-12-26 20:26 UTC, johko approved these changes
LGTM :+1:

2023-12-26 22:21 UTC, WilliamBonvini requested changes

2023-12-26 22:21 UTC, WilliamBonvini commented on chapters/en/Unit 5 - Generative Models/PRACTICAL APPLICATIONS & CHALLENGES/Ethical Issues.mdx
> +    - Future Scope
I would replace the capital letters also here ("Approaches" --> "approaches" and "Scope" --> "scope")

2023-12-26 22:21 UTC, WilliamBonvini commented on chapters/en/Unit 5 - Generative Models/PRACTICAL APPLICATIONS & CHALLENGES/Ethical Issues.mdx
> +- **Advanced detection and mitigation techniques**: Researchers will ideally develop more advanced techniques for detecting and mitigating the harms associated with AI-edited images. But is like a ca
"But is like a cat and dog game" --> "But **it's** like a **cat-and-mouse** game"

2023-12-27 03:54 UTC, hwaseem04 commented
> Looking good so far! I think something to consider if there's time is this [article](https://www.technologyreview.com/2023/10/23/1082189/data-poisoning-artists-fight-generative-ai/). It comes from the following [text](https://arxiv.org/abs/2310.13828). It talks about scraping copyright data for generative models.

That is an interesting read. Probably will add it as a reference reading material

2023-12-27 04:01 UTC, hwaseem04 commented
> Why there are all those empty README.md files? Maybe they don't cause any problem, but I don't think they are supposed to be there, right?

Thank you for pointing out. Those empty files are removed.

2023-12-27 04:01 UTC, hwaseem04 commented on chapters/en/Unit 5 - Generative Models/PRACTICAL APPLICATIONS & CHALLENGES/Ethical Issues.mdx
> +This is a rapidly evolving field, and it is crucial to stay informed about the latest developments.
That sounds good, will try to add some.

2023-12-27 08:10 UTC, merveenoyan approved these changes
LGTM!

2023-12-27 08:10 UTC, merged