Added video processing section (Unit 7 - introduction )
johko/computer-vision-course pull request #314
Opened 2024-06-18 02:51 UTC by jungnerd

Added introduction of video processing and updated credits

2024-06-20 00:41 UTC, ATaylorAerospace commented on chapters/en/unit7/video-processing/introduction-to-video.mdx
> +Video processing is a dynamic and vital area within AI and CV, offering numerous applications and presenting unique challenges. Its importance in modern technology continues to grow, fueled by advanc
```suggestion
Video processing is a dynamic and vital area within AI and CV, offering numerous applications and presenting unique challenges. Its importance in modern technology continues to grow, fueled by advancements in deep learning and the increasing availability of video data. In the following sections, we will dive deeper into deep learning for video processing. You'll explore state-of-the-art models including 3D CNNs and transformers.  

```

2024-06-20 00:47 UTC, ATaylorAerospace requested changes
Thanks for adding this intro. Just a couple of small nits have been noted

2024-06-20 00:47 UTC, ATaylorAerospace commented on chapters/en/unit7/video-processing/introduction-to-video.mdx
> +In the research field of computer vision (CV) and artificial intelligence (AI), video processing is all about automatically analyzing video data to understand and interpret both temporal and spatial
```suggestion
In the research field of computer vision (CV) and artificial intelligence (AI), video processing involves automatically analyzing video data to understand and interpret both temporal and spatial features. Video data is simply a sequence of time-varying images, where the information is digitized both spatially and temporally. This allows us to perform detailed analysis and manipulation of the content within each frame of the video.

```

2024-06-20 01:05 UTC, jungnerd commented
> Thanks for adding this intro. Just a couple of small nits have been noted

Thanks for the review 😍

2024-06-20 01:45 UTC, ATaylorAerospace approved these changes

2024-07-04 01:14 UTC, jungnerd commented
@merveenoyan Would you mind reviewing this for merge?

2024-07-13 16:09 UTC, cjfghk5697 commented
I'm not sure, but it seems like we should add this topic to the "toctree.yml".

2024-07-19 20:09 UTC, johko requested changes
Thanks for contributing! I added some small proposals, actually all  capitalization stuff, for consistency within the course.

But great work :+1:

2024-07-19 20:09 UTC, johko commented on chapters/en/unit7/video-processing/introduction-to-video.mdx
> +In the research field of computer vision (CV) and artificial intelligence (AI), video processing involves automatically analyzing video data to understand and interpret both temporal and spatial feat
To be consistent in the course, I think we should capitalize Computer Vision and Artificial Intelligence
```suggestion
In the research field of Computer Vision (CV) and Artificial Intelligence (AI), video processing involves automatically analyzing video data to understand and interpret both temporal and spatial features. Video data is simply a sequence of time-varying images, where the information is digitized both spatially and temporally. This allows us to perform detailed analysis and manipulation of the content within each frame of the video.

```

2024-07-19 20:09 UTC, johko commented on chapters/en/unit7/video-processing/introduction-to-video.mdx
> +Video processing has become increasingly important in today's technology-driven world, thanks to the rapid advancements in deep learning (DL) and AI. Traditionally, DL research has focused on images,
```suggestion
Video processing has become increasingly important in today's technology-driven world, thanks to the rapid advancements in Deep Learning (DL) and AI. Traditionally, DL research has focused on images, speech, and text, but video data offers a unique and valuable opportunity for research due to its extensive size and complexity. With millions of videos uploaded daily on platforms like YouTube, video data has become a rich resource, driving AI research and enabling groundbreaking applications.

```

2024-07-19 20:09 UTC, johko commented on chapters/en/unit7/video-processing/introduction-to-video.mdx
> +Video processing is a dynamic and vital area within AI and CV, offering numerous applications and presenting unique challenges. Its importance in modern technology continues to grow, fueled by advanc
```suggestion
Video processing is a dynamic and vital area within AI and CV, offering numerous applications and presenting unique challenges. Its importance in modern technology continues to grow, fueled by advancements in deep learning and the increasing availability of video data. In the following sections, we will dive deeper into deep learning for video processing. You'll explore state-of-the-art models including 3D CNNs and Transformers.  

```

2024-07-20 04:02 UTC, jungnerd commented
> Thanks for contributing! I added some small proposals, actually all capitalization stuff, for consistency within the course.
> 
> But great work 👍

Thanks for the review! I reflected your review and committed it!

2024-07-20 06:22 UTC, johko approved these changes
Thanks for the quick editing :)
Will merge now

2024-07-20 06:58 UTC, johko commented
Looks like the quality check fails @jungnerd. Can you run `make style` from the root of your forked repository and commit the changed code? That should fix it

2024-07-21 12:25 UTC, jungnerd commented
> Looks like the quality check fails @jungnerd. Can you run `make style` from the root of your forked repository and commit the changed code? That should fix it

@johko 
It looks like the Makefile does not contain a target for `style`, so `make style` fails. Should I add a style target to the Makefile to address this issue?

2024-07-23 20:36 UTC, johko commented
> > Looks like the quality check fails @jungnerd. Can you run `make style` from the root of your forked repository and commit the changed code? That should fix it
> 
> @johko It looks like the Makefile does not contain a target for `style`, so `make style` fails. Can I add a style target to the Makefile to address this issue?

Ah yes, you're right. Strange, I thought it would be in there. I'll try to figure out what exactly make style should do and will either add it to he makefile myself and create a PR or tell you which command to run to fix the formatting @jungnerd

2024-07-23 20:48 UTC, johko commented
I just created a PR which adds the command to the makefile: #324 
It also fixes the file which was not correctly formatted (turns out it slipped in through an other PR and is not your fault). 

As soon as my PR is merged, you can merge the changes into your branch and it should be good.

2024-07-24 05:05 UTC, jungnerd commented
> I just created a PR which adds the command to the makefile: #324 It also fixes the file which was not correctly formatted (turns out it slipped in through an other PR and is not your fault).
> 
> As soon as my PR is merged, you can merge the changes into your branch and it should be good.

Great, thanks for checking 👍
I'll be waiting for your PR to be merged.

2024-08-14 08:04 UTC, johko commented
@jungnerd I just merged the other PR (finally), so if you pull the upstream/main branch, the quality check should also work ;)

2024-08-14 08:32 UTC, johko commented
nevermind, I could update it from here and will merge now :slightly_smiling_face:

2024-08-14 08:32 UTC, merged