Update knowledge-distillation.mdx
johko/computer-vision-course pull request #318
Opened 2024-06-24 12:24 UTC by ghassen-fatnassi

just some knowledge i learned , though it was good to share , thanks HF

2024-06-25 01:07 UTC, mmhamdy reviewed
Thanks for the suggestions! Just a couple of comments.

2024-06-25 01:07 UTC, mmhamdy commented on chapters/en/unit3/vision-transformers/knowledge-distillation.mdx
> +1. **Entropy Gain**: Distillation helps in transferring the "dark knowledge" (i.e., soft probabilities) from the teacher model to the student model, which contains more information than hard labels.
What do you mean by "Entropy Gain"?

2024-06-25 01:07 UTC, mmhamdy commented on chapters/en/unit3/vision-transformers/knowledge-distillation.mdx
> +1. **Entropy Gain**: Distillation helps in transferring the "dark knowledge" (i.e., soft probabilities) from the teacher model to the student model, which contains more information than hard labels.
```suggestion
1. **Entropy Gain**: One way distillation works is by transferring the "dark knowledge" (i.e., soft probabilities) from the teacher model to the student model, which contains more information than hard labels. This extra information helps the student model generalize better.
```

2024-06-25 09:44 UTC, ghassen-fatnassi commented on chapters/en/unit3/vision-transformers/knowledge-distillation.mdx
> +1. **Entropy Gain**: Distillation helps in transferring the "dark knowledge" (i.e., soft probabilities) from the teacher model to the student model, which contains more information than hard labels.
thanks a lot for your fast reply , you are right , entropy gain has no sense , the more convenient term will likely be "information gain" since by absorbing that cross entropy loss between the 2 distributions (student model output & teacher model output) the model gains "more information" than by absorbing cross entropy loss between (student & groundtruth) 
i got confused between the two terms.

2024-07-19 20:21 UTC, johko requested changes
Thanks for the contribution and I really like the facts you added :+1: 

I left some suggestions to make it even more informative for people going through the course.

2024-07-19 20:21 UTC, johko commented on chapters/en/unit3/vision-transformers/knowledge-distillation.mdx
> +Knowledge distillation became very useful when the machine learning community realized there was great potential in deploying AI models on edge devices. However, we can't just deploy a model that's 1
```suggestion
Knowledge distillation became very useful when the machine learning community realized there was great potential in deploying AI models on edge devices. However, we can't just deploy a model that's 1 GB in size and has a 1-second latency for users to use — it’s too big and too slow. These drawbacks are mainly caused by the big number of weights of the model. From that moment, people started distilling models and reducing their parameter count by more than 90% with negligible performance drops.
```

2024-07-19 20:21 UTC, johko commented on chapters/en/unit3/vision-transformers/knowledge-distillation.mdx
> +1. **Entropy Gain**: One way distillation works is by transferring the "dark knowledge" (i.e., soft probabilities) from the teacher model to the student model, which contains more information than ha
This is a really interesting fact, could you maybe explain soft probabilities a bit more? Our target audience are mainly beginners, so I think it would help to give some more details about that.

2024-07-19 20:21 UTC, johko commented on chapters/en/unit3/vision-transformers/knowledge-distillation.mdx
> +2. **Coherent Gradient Updates**: The gradients provided by the teacher model's soft targets help in more stable and coherent updates during training, resulting in a smoother training process for the
Similar to above, maybe you can explain what you mean by soft targets

2024-07-19 20:23 UTC, johko commented
And feel free to add your name in this file in the Vision Transformer part @ghassen-fatnassi: https://github.com/johko/computer-vision-course/blob/main/chapters/en/unit0/welcome/welcome.mdx

2024-08-15 13:25 UTC, ghassen-fatnassi commented
done!

2024-08-20 08:53 UTC, johko approved these changes
Thanks for the changes @ghassen-fatnassi , LGTM :+1:

2024-08-20 14:15 UTC, mmhamdy reviewed
Hey @ghassen-fatnassi, thanks for this amazing elaboration! 😀 My main issue, as I mentioned previously, is the "entropy gain" section. I think the term is a little bit confusing. In this section, you're explaining what entropy is but it's not clear how this relates to knowledge distillation. I understand you're trying to convey the important role that soft targets play in the student's learning, and how it contain much more information than hard labels, but it would be great to make this connection explicit in this section.

2024-08-22 06:12 UTC, mmhamdy approved these changes
Thanks! Looks good! 👍

2024-09-24 14:36 UTC, ghassen-fatnassi commented
there are still merge conflicts to be resolved , idk what should i do as i'm not the code owner and this is still in the back of my head!

2024-10-02 22:21 UTC, ghassen-fatnassi commented
what do i do hhhhh *
@mmhamdy
@johko

2024-10-02 23:51 UTC, mmhamdy commented
Hey 👋 we have some conflicts in these two files: `welcome.mdx` and `vision-transformer-for-objection-detection.mdx`. can you cancel your changes in these two and create separate PR for them?

2024-10-03 01:56 UTC, closed without merging