Overview of Previous SOTA Models
johko/computer-vision-course pull request #320
Opened 2024-07-02 03:54 UTC by cjfghk5697

Added overview of previous SOTA models in unit 7

2024-07-02 07:51 UTC, cjfghk5697 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +</TIP>
```suggestion
</Tip>
```

2024-07-02 23:47 UTC, sezan92 reviewed
i plan to review

2024-07-09 12:10 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +# Overview of Previous SOTA Models – Including 3D CNNs like (2+1)D Resnets and Two Stream Nets
```suggestion
# Overview of the previous SOTA models
```

2024-07-09 12:11 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +State-Of-The-Art(SOTA) refers to the best models that can be used to achieve results in a task.
```suggestion
```

I think this is redundant in this unit 7. the definition of SOTA can be googled by the readers.

2024-07-09 12:11 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +### General Trend:
```suggestion
### General trend:
```

2024-07-09 12:12 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +# Previous SOTA Models in Video Processing
```suggestion
# Previous SOTA models in Video Processing
```

2024-07-09 12:12 UTC, sezan92 reviewed
To be continued

2024-07-12 18:13 UTC, bellabf reviewed
Hi! 

Thank you so much for this PR! It will make a great addition to the course. I left some suggestions, mostly re-wording and formatting some aspects of the text to better match the style and format of the other .mdx in the course. 

Note that following the new guidelines for contribution, major contributions to the course are not merged directly into the main branch. Instead, they should be merged on the staging branch (johko:stage). I don't see a problem in reviewing it here and then reopening the PR there once it is all good to go. 

Thank you so much again. Really good work!

2024-07-12 18:13 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +- Researchers are exploring deeper 3D CNN architectures along with the development of larger video datasets like Kinetics.
```suggestion
Currently, researchers are exploring deeper 3D CNN architectures. Another promising approach is combining 3D CNNs with other techniques like attention mechanisms. Alongside that, there is a push for developing larger video datasets like Kinetics.
```

2024-07-13 14:28 UTC, cjfghk5697 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +
I totally agree that including a table of previous loss values would be beneficial for the reader. I will commit the updated version with the new table.

2024-07-13 14:30 UTC, cjfghk5697 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +
Sure! I'll include a brief description of the dataset with the link.

2024-07-13 15:16 UTC, cjfghk5697 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +In this paper, they applied the architecture of ResNets to 3D CNNs. This model introduces deeper models for the 3D CNNs and achieves a lower loss value.
```suggestion
Standard 3D CNNs extend the concept to capture spatial and temporal information simultaneously using 3D kernels (2D spatial information + temporal information). A drawback of this model is that the large number of parameters in 3D CNNs makes them slower and more computationally intensive than 2D CNNs. Therefore, 3D CNNs typically have fewer layers compared to the deeper architectures of 2D CNNs.

In this paper, the authors applied the ResNet architecture to 3D CNNs. This approach introduces deeper models for 3D CNNs and achieves higher accuracy, thereby improving performance.
```

2024-07-13 15:30 UTC, cjfghk5697 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +Currently, researchers are exploring deeper 3D CNN architectures. Another promising approach is combining 3D CNNs with other techniques like attention mechanisms. Alongside that, there is a push for
```suggestion
Currently, researchers are exploring deeper 3D CNN architectures. Another promising approach is combining 3D CNNs with other techniques like attention mechanisms. Alongside that, there is a push for developing larger video datasets like [Kinetics](https://github.com/google-deepmind/kinetics-i3d).

> The Kinetics dataset is a large-scale, high-quality video dataset commonly used for human action recognition research. It contains hundreds of thousands of video clips that cover a wide range of human activities.
>
```

2024-07-13 15:42 UTC, cjfghk5697 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +
```suggestion
| Method                        | Clip@1 Accuracy | Video@1 Accuracy | Video@5 Accuracy |
|-------------------------------|--------|---------|---------|
| DeepVideo [16]                | 41.9   | 60.9    | 80.2    |
| C3D [36]                      | 46.1   | 61.1    | 85.2    |
| 2D ResNet-152 [13]            | 46.5  | 64.6    | 86.4    |
| Conv pooling [42]             | -      | 71.7    | 90.4    |
| P3D [25]                      | 47.9  | 66.4   | 87.4   |
| R3D-RGB-8frame                | 53.8   | -       | -       |
| R(2+1)D-RGB-8frame            | 56.1   | 72.0    | 91.2    |
| R(2+1)D-Flow-8frame           | 44.5   | 65.5    | 87.2    |
| R(2+1)D-Two-Stream-8frame     | -      | 72.2    | 91.4    |
| R(2+1)D-RGB-32frame           | **57.0**   | **73.0**    | **91.5**    |
| R(2+1)D-Flow-32frame          | 46.4   | 68.4    | 88.7    |
| R(2+1)D-Two-Stream-32frame    | -      | **73.3**    | **91.9**    |
```

2024-07-13 15:44 UTC, cjfghk5697 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +| R(2+1)D-Two-Stream-32frame    | -      | **73.3**    | **91.9**    |
```suggestion

| Method                        | Clip@1 Accuracy | Video@1 Accuracy | Video@5 Accuracy |
|-------------------------------|--------|---------|---------|
| DeepVideo                | 41.9   | 60.9    | 80.2    |
| C3D                     | 46.1   | 61.1    | 85.2    |
| 2D ResNet-152            | 46.5  | 64.6    | 86.4    |
| Conv pooling             | -      | 71.7    | 90.4    |
| P3D                      | 47.9  | 66.4   | 87.4   |
| R3D-RGB-8frame                | 53.8   | -       | -       |
| R(2+1)D-RGB-8frame            | 56.1   | 72.0    | 91.2    |
| R(2+1)D-Flow-8frame           | 44.5   | 65.5    | 87.2    |
| R(2+1)D-Two-Stream-8frame     | -      | 72.2    | 91.4    |
| R(2+1)D-RGB-32frame           | **57.0**   | **73.0**    | **91.5**    |
| R(2+1)D-Flow-32frame          | 46.4   | 68.4    | 88.7    |
| R(2+1)D-Two-Stream-32frame    | -      | **73.3**    | **91.9**    |

```

2024-07-13 15:49 UTC, cjfghk5697 commented
@bellabf @sezan92 Thank you for reviewing. I'm afraid my initial contribution might not be sufficient. Therefore, I am revising the document based on your feedback. Could you please review this PR?

2024-07-13 19:28 UTC, bellabf reviewed
Hi, 

Thank you for the rapid iteration. I fixed some nits (like the spaces and some punctuation). Otherwise, it looks really good to me.  After we fix these last bits, can you move the PR to stage branch so I can approve it?

note: you would still need the approval of other reviewers and a code owner, but at least you would already have one :)

2024-07-13 19:28 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +
```suggestion
```

2024-07-13 19:28 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +The success of deep learning, particularly CNNs trained on massive datasets like ImageNet,  revolutionized image recognition. This trend continues in video processing. However, video data introduces
```suggestion
The success of deep learning, particularly CNNs trained on massive datasets like ImageNet, revolutionized image recognition. This trend continues in video processing. However, video data introduces another dimension compared to static images: time. This simple change introduced a new set of challenges that CNN trained in static images were not built to deal with. 
```

2024-07-13 19:28 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +
```suggestion
```

2024-07-13 19:28 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +Experiments showed that 3D ResNets, especially deeper ones like ResNet-34, outperform models like C3D, particularly on larger datasets. Pretrained models like Sports-1M C3D can help mitigate overfitt
```suggestion
Experiments showed that 3D ResNets (especially deeper ones like ResNet-34) outperform models like C3D, particularly on larger datasets. Pretrained models like Sports-1M C3D can help mitigate overfitting on smaller datasets. Overall, 3D ResNets effectively leverage deeper architectures to capture complex spatiotemporal patterns in video data.
```

2024-07-13 19:28 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +> The Kinetics dataset is a large-scale, high-quality video dataset commonly used for human action recognition research. It contains hundreds of thousands of video clips that cover a wide range of hu
```suggestion
The Kinetics dataset is a large-scale high-quality video dataset commonly used for human action recognition research. It contains hundreds of thousands of video clips that cover a wide range of human activities.
```

2024-07-13 19:28 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +>
```suggestion
```

2024-07-13 19:28 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +
```suggestion
```

2024-07-13 19:28 UTC, bellabf commented on chapters/en/unit0/welcome/welcome.mdx
>  - Reviewers: [Ameed Taylor](https://github.com/atayloraerospace)
```suggestion
- Reviewers: [Ameed Taylor](https://github.com/atayloraerospace), [Isabella Bicalho-Frazeto](https://github.com/bellabf)
```

2024-07-13 19:28 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +
thank you for taking care of this <3

2024-07-13 19:28 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +
thank you!

2024-07-13 19:29 UTC, bellabf commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +
Thank you! I like it a lot now with the table :) It is easier to see how it improved the previous SOTA

2024-07-13 19:32 UTC, bellabf commented
> @bellabf @sezan92 Thank you for reviewing. I'm afraid my initial contribution might not be sufficient. Therefore, I am revising the document based on your feedback. Could you please review this PR?

Hi @cjfghk5697, I think your contribution is awesome! It will add value to the course that we did not cover before. Since it is a mdx file, it usually takes some revisions so it looks perfect to be merged (but please don't be discouraged by it!). Keep up the good work :hugs:

2024-07-14 01:21 UTC, cjfghk5697 commented
Hi @bellabf Thank you for the encouragement! I switched branches and committed your suggestions. Your review is a great help to me. Thanks again🤗

2024-07-15 19:50 UTC, bellabf commented
Hi @cjfghk5697,

I didn't realize that the stage was so behind the main branch.  I opened another PR to the stage branch so it is in sync with the main again. That way, your PR will be more atomic and easier to merge.

In the meantime, would @sezan92 (or maybe @mmhamdy  @ATaylorAerospace) would be available to review this PR 🙏? It would be a nice addition to unit 7. 

Thanks again everyone!! 🤗

2024-07-18 03:56 UTC, sezan92 commented
@cjfghk5697 it seems there are 93 files! which files exactly you wrote?

2024-07-19 20:28 UTC, johko commented
Oh damn, sorry for the mess up with the branches @cjfghk5697 and thanks for your contribution (and actually doing it right and PRing to the stage branch). 

If I'm not mistaken the main part added is this file: chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx @sezan92

2024-07-21 17:08 UTC, cjfghk5697 commented
@sezan92 my apologies for the late reply. I added the overview-of-previous-sota-models.mdx file.

2024-07-23 02:38 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +Standard 3D CNNs extend the concept to capture spatial and temporal information simultaneously using 3D kernels (2D spatial information + temporal information). A drawback of this model is that the l
```suggestion
Standard 3D CNNs extend the concept to simultaneously capture spatial and temporal information using 3D kernels (2D spatial information + temporal information). A drawback of this model is that the large number of parameters result the training being more computationally intensive and hence slower than the 2D version. Therefore, the 3D version of the ConvNets typically has fewer layers than the deeper architectures of 2D CNNs.
```

2024-07-23 02:39 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +In this paper, the authors applied the ResNet architecture to 3D CNNs. This approach introduces deeper models for 3D CNNs and achieves higher accuracy, thereby improving performance.
```suggestion
In this paper, the authors applied the ResNet architecture to the 3D CNNs. This approach introduces deeper models for 3D CNNs and achieves higher accuracy.
```

2024-07-23 02:40 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +Experiments showed that 3D ResNets (especially deeper ones like ResNet-34) outperform models like C3D, particularly on larger datasets. Pretrained models like Sports-1M C3D can help mitigate overfitt
```suggestion
Experiments showed that the 3D ResNets (especially deeper ones like the ResNet-34) outperform models like the C3D, particularly on larger datasets. Pretrained models like Sports-1M C3D can help mitigate overfitting on smaller datasets. Overall, 3D ResNets effectively leverage deeper architectures to capture complex spatiotemporal patterns in the video data.
```

2024-07-23 02:40 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +(2+1)D ResNets is inspired by 3D ResNets. Howver, a key difference is how the layers are structured. This architecture introduces a combination of 2D convolution and 1D convolution:
```suggestion
(2+1)D ResNets are inspired by the 3D ResNets. However, a key difference lies in how the layers are structured. This architecture introduces a combination of 2D convolution and 1D convolution:
```

2024-07-23 02:40 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +- 2D convolution capture spatial features within a frame.
```suggestion
- The 2D convolution captures the spatial features within a frame.
```

2024-07-23 02:41 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +- 1D convolution capture motion information across consecutive frames.
```suggestion
- The 1D convolution captures the motion information across the consecutive frames.
```

2024-07-23 02:42 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +    - Decomposition facilitates the optimization, yielding in practice both a lower training loss and a lower testing loss.
```suggestion
    - Decomposition facilitates the optimization, yielding in lower train loss and test loss in practice.
```

2024-07-23 02:43 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +[Papers with Code](https://paperswithcode.com/) is a free and open resource that provides access to research papers in the field of machine learning, along with the code implementations of the method
```suggestion
```

Not needed I believe

2024-07-23 02:44 UTC, sezan92 commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +The evolution of video analysis models has been fascinating to witness. These models were heavily influenced by other models which once were the state-of-the-art. For example, Two-StreamNets motivate
```suggestion
The evolution of video analysis models has been fascinating to witness. These models were heavily influenced by other SOTA models. For example, Two-StreamNets was motivated by the  ConvNets and (2+1)D ResNets were inspired by the 3D ResNets. As the research progresses, one can expect even more advanced architectures and techniques to emerge in the future.
```

2024-07-23 02:45 UTC, sezan92 requested changes
Fine, certain grammatical issues.

2024-07-23 21:18 UTC, johko requested changes
Cool overview, for someone like me, who does not know too much about video processing it gives me a good idea how things developed and what might happen next :+1: 

Left some mostly grammatical comments

2024-07-23 21:18 UTC, johko commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +The success of deep learning, particularly CNNs trained on massive datasets like ImageNet, revolutionized image recognition. This trend continues in video processing. However, video data introduces a
Capitalization for consistency in the course
```suggestion
The success of Deep Learning, particularly CNNs trained on massive datasets like ImageNet, revolutionized image recognition. This trend continues in video processing. However, video data introduces another dimension compared to static images: time. This simple change introduced a new set of challenges that CNN trained in static images were not built to deal with. 
```

2024-07-23 21:18 UTC, johko commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +### General trend:
Is there a reason you have 3x# instead of 2x# as in the other headings further down?
Also I think the second word should be capitalized as well
```suggestion
### General Trend:
```

2024-07-23 21:18 UTC, johko commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +# Previous SOTA models in Video Processing
```suggestion
# Previous SOTA Models in Video Processing
```

2024-07-23 21:18 UTC, johko commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +This paper extended deep Convolution Networks(ConvNets) to perform action-recognition in video data.
```suggestion
This paper extended Deep Convolutional Networks(ConvNets) to perform action-recognition in video data. 
```

2024-07-23 21:18 UTC, johko commented on chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx
> +[Papers with Code](https://paperswithcode.com/) is a free and open resource that provides access to research papers in the field of machine learning, along with the code implementations of the method
I agree that it is not necessarily needed, but from my side it could also stay in, because it can be a valuable tip for beginners. Maybe just move it below the conclusion part, so it does not break the reading flow

2024-07-24 15:58 UTC, cjfghk5697 commented
@sezan92 @johko 
Thank you very much for your review. Your feedback helped me identify and correct the areas I had missed, greatly improving the document. I sincerely appreciate your assistance!

2024-08-14 08:05 UTC, johko approved these changes
LGTM :+1:

2024-08-14 10:22 UTC, sergiopaniego approved these changes
Great contribution! Thanks 🤗

2024-08-14 10:30 UTC, merged