Copy-Editing/Grammatical Fixes: Chapters 2-13
johko/computer-vision-course pull request #326
Opened 2024-08-01 21:04 UTC by ericoulster

I made small sentence structure changes throughout the course to improve clarity.

Issues are relatively small, and usually involve less than a sentence of revisions across a handful of modules.

2024-08-02 00:41 UTC, mmhamdy approved these changes
Looks great! Thanks for the fixes 🙂

2024-08-12 13:11 UTC, sergiopaniego commented
I can't approve the changes but they look good to me 😄

2024-08-12 15:30 UTC, sergiopaniego approved these changes

2024-08-14 08:19 UTC, johko approved these changes
Thanks for the fixes :+1: LGTM

2024-08-14 08:37 UTC, johko requested changes
Spotted a little problem in hindsight, I left a comment how to fix it

2024-08-14 08:37 UTC, johko commented on chapters/en/unit3/vision-transformers/vision-transformer-for-object-detection.mdx
I just saw that one of the workflows failed and saw that you corrected the name of this file. You will also need to change it in the _toctree.yml, located at chapters/en/_toctree.yml

2024-08-14 13:39 UTC, ericoulster commented on chapters/en/unit3/vision-transformers/vision-transformer-for-object-detection.mdx
Makes sense. 

I pushed the change you mentioned and the automated tests appear to be green now.

2024-08-14 18:37 UTC, johko approved these changes
Thanks for the quick response :+1:

2024-08-14 18:38 UTC, merged