Yolo v1
johko/computer-vision-course pull request #344
Opened 2024-09-25 10:25 UTC by sezan92

## Objective 

This PR is about adding information about Yolov1 . This PR is contributed by @sitamgithub-MSIT @themurtazanazir anthony  and myself.

2024-09-27 22:29 UTC, ATaylorAerospace reviewed
Made a few punctuation and grammar corrections.

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +So far, we have seen the basic characteristics of YOLO and how it allows for highly accurate and fast predictions. This was actually the first version of YOLO, called YOLOv1. YOLOv1 was released in 2
```suggestion
So far, we have seen the basic characteristics of YOLO and how it allows for highly accurate and fast predictions. This was actually the first version of YOLO, called YOLOv1. YOLOv1 was released in 2015, and since then, multiple versions have been released. It was groundbreaking in terms of accuracy and speed, since it introduced the concept of using a single convolutional neural network (CNN) that processes the entire image at once, dividing it into an S × S grid. Each grid cell predicts bounding boxes and class probabilities directly. However, it suffered from poor localization and detection of multiple objects in small image areas. In the following years, many new versions were released by different teams to gradually improve the accuracy, speed, and robustness.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +After a year of releasing the first version, YOLOv2[5] came out. The improvements focused on both accuracy and speed but also dealt with the localization problem. First, YOLOv2 replaced YOLOv1’s back
```suggestion
A year after releasing the first version, YOLOv2[5] came out. The improvements focused on both accuracy and speed, but also dealt with the localization problem. First, YOLOv2 replaced YOLOv1’s backbone architecture with Darknet-19, which is a variant of the Darknet architecture. Darknet-19 is lighter than the previous version’s backbone, and it consists of 19 convolutional layers followed by max-pooling layers. This led to YOLOv2 having the ability to capture more information. Also, it applied batch normalization to all convolutional layers and hence removed the dropout layers, dealing with the overfitting problem and increasing the mAP. It also introduced the concept of anchor boxes, which added prior knowledge to the width and height of the detected boxes (specifically, they used anchor boxes). Additionally, to deal with the poor localization, YOLOv2 predicted the class and objects for every anchor box and grid cell (now 13x13). So we have a maximum (for 5 anchor boxes) of 13x13x5 = 845 boxes.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +YOLOv3[6] again improved significantly the detection speed and accuracy by replacing the Darknet-19 architecture with the more complex but efficient Darknet-53. Also, it dealt with the localization p
```suggestion
YOLOv3[6] again significantly improved the detection speed and accuracy by replacing the Darknet-19 architecture with the more complex but efficient Darknet-53. Also, it dealt with the localization problem better by using three different scales for object detection (13x13, 26x26, and 52x52 grids). This helped find objects of different sizes in the same area. It increased the bounding boxes to: 13 x 13 x 3 + 26 x 26 x 3 + 52 x 52 x 3 = 10,647. Non-Maximum Suppression (NMS) was still used to filter out redundant overlapping boxes.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +Back in 2020, YOLOv4[7] became one of the best detection models in terms of speed and accuracy achieving state-of-the-art results on object detection benchmarks. The authors changed the backbone arch
```suggestion
Back in 2020, YOLOv4[7] became one of the best detection models in terms of speed and accuracy, achieving state-of-the-art results on object detection benchmarks. The authors changed the backbone architecture again, opting for the faster and more accurate CSPDarknet53[8]. An important improvement of this version was the optimization for efficient resource utilization, making it suitable for deployment on various hardware platforms, including edge devices. Also, it included a number of augmentations before training that further improved the model's generalization. The authors included this improvement in a set of methodologies called bag-of-freebies. Bag-of-freebies are optimization methods that have a cost to the training process but aim to increase the model's accuracy in real-time detection without increasing the inference time.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +YOLOv5[9] translated the Darknet framework (written in C) to the more flexible and ease of use Pytorch framework. This version automated the previous anchor detection mechanism introducing the auto-a
```suggestion
YOLOv5[9] translated the Darknet framework (written in C) to the more flexible and easy-to-use PyTorch framework. This version automated the previous anchor detection mechanism, introducing the auto-anchors. Auto-anchors train the model anchors automatically to match your data. During training, YOLO automatically uses k-means initially and genetic methods to evolve the new better-matched anchors and places them back into the YOLO model. Also, it offers different types of models that depend on the hardware constraints, with names similar to today’s YOLOv8 models: YOLOv5s, YOLOv5m, YOLOv5l, and YOLOv5x.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +4) Introducttion to new types of loss functions such as, Varifocal Loss for Classification. IoU Series Loss  for Boundig Box Regression, and Distribution Focal Loss.
```suggestion
4) Introduction to new types of loss functions such as, Varifocal Loss for Classification. IoU Series Loss  for Bounding Box Regression, and Distribution Focal Loss.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +1) Reparameterization using the RepVGG technique. Which is a modified version of VGG with skip connections. During inference, these connections are fused to improve the speed.
```suggestion
1) Reparameterization using the RepVGG technique, which is a modified version of VGG with skip connections. During inference, these connections are fused to improve the speed.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +In 2023, YOLOv6 v3[12] was released with the title: "YOLOv6 v3.0: A Full-Scale Reload," which introduced enhancements to the network architecture and training scheme, once again advancing speed and a
```suggestion
In 2023, YOLOv6 v3[12] was released with the title "YOLOv6 v3.0: A Full-Scale Reload,", which introduced enhancements to the network architecture and training scheme, once again advancing speed and accuracy (evaluated on the COCO dataset) compared to previously released versions.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +YOLOv7 was released with the paper name: “YOLOv7: Trainable bag-of-freebies sets new state-of-the-art for real-time object detectors”[13][14] by the authors of YOLOv4.Specifically, this version of ba
```suggestion
YOLOv7 was released with the paper titled “YOLOv7: Trainable bag-of-freebies sets new state-of-the-art for real-time object detectors”[13][14] by the authors of YOLOv4. Specifically, this version of bag-of-freebies includes a new label assignment method called coarse-to-fine lead-guided label assignment and uses gradient flow propagation paths to analyze how re-parameterized convolution should be combined with different networks. They also proposed “extend” and “compound scaling” methods for the real-time object detector that can effectively utilize parameters and computation. Again, all these improvements took real-time object detection to a new state-of-the-art, outperforming previous releases.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +YOLOv8[15], developed by Ultralytics in 2023 became again the new SOTA. It introduced improvements on the backbone and neck, alongside an anchor-free approach which eliminates the need for predefined
```suggestion
YOLOv8[15], developed by Ultralytics in 2023, became again the new SOTA. It introduced improvements on the backbone and neck alongside an anchor-free approach, which eliminates the need for predefined anchor boxes. Instead, predictions are made directly. This version supports a wide range of vision tasks, including classification, segmentation, and pose estimation. Additionally, YOLOv8 has scaling capabilities with pre-trained models available in various sizes: nano, small, medium, large, and extra-large, and can be easily fine-tuned on custom datasets.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +YOLOv9 was released with the paper name: “YOLOv9: Learning What You Want to Learn Using Programmable Gradient Information”[16][17] by the same authors of YOLOv7 and YOLOv4 . This paper highlights the
```suggestion
YOLOv9 was released with the paper titled “YOLOv9: Learning What You Want to Learn Using Programmable Gradient Information”[16][17] by the same authors as YOLOv7 and YOLOv4. This paper highlights the issue of information loss that existing methods and architectures have during layer-by-layer feature extraction and spatial transformation. To address this issue, the authors proposed:
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +With these changes, YOLOv9 set new benchmarks on the MS COCO challenge
```suggestion
With these changes, YOLOv9 set new benchmarks on the MS COCO challenge.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +This short chapter presented the history/evolution of YOLO in a linear way. However, this is not the case—many other versions of YOLO were released in parallel. Notice the release of YOLOv4 and YOLOv
```suggestion
This short chapter presented the history/evolution of YOLO in a linear way. However, this is not the case—many other versions of YOLO were released in parallel. Notice the release of YOLOv4 and YOLOv5 in the same year. Other versions that we did not cover include YOLOvX (2021), which was based on YOLOv3 (2018), and YOLOR (2021), which was based on YOLOv4 (2020), and many others.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +Also, It is important to understand that the selection of the ‘best’ model version depends on the user requirements such as speed, accuracy, hardware limitations, and user-friendliness. For example,
```suggestion
Also, it is important to understand that the selection of the ‘best’ model version depends on the user requirements, such as speed, accuracy, hardware limitations, and user-friendliness. For example, YOLOv2 is very good at speed. YOLOv3 provides a balance between accuracy and speed. YOLOv4 has the best ability for adapting or being compatible across different hardware.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +In addition, many grid cells do not contain objects, the confidence is close to zero and thus the grid cells containing the objects often overpower the gradients. This makes the network unstable duri
```suggestion
In addition, many grid cells do not contain objects. The confidence is close to zero and thus the grid cells containing the objects often overpower the gradients. This makes the network unstable during training.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +To rectify, we also weigh the loss from the confidence predictions in the grid cells which do not contain objects less than the grid cells which contain objects. We use a separate weight for the conf
```suggestion
To rectify, we also weigh the loss from the confidence predictions in the grid cells that do not contain objects lower than in the grid cells that contain objects. We use a separate weight for the confidence loss called $\lambda_{\text{noobj}}$, which is usually set to 0.5.
```

2024-09-27 22:29 UTC, ATaylorAerospace commented on chapters/en/unit2/cnns/yolo.mdx
> +In rare cases, for large objects, the network tends to predict multiple boxes from multiple grid cells. To eliminate duplicate detections, we use a technique called non-maximum suppression (NMS). NMS
```suggestion
In rare cases, for large objects, the network tends to predict multiple boxes from multiple grid cells. To eliminate duplicate detections, we use a technique called Non-Maximum Suppression (NMS). NMS works by selecting the box with the highest confidence score and eliminating all other boxes with an IOU greater than a threshold. This is done iteratively until no overlapping boxes remain.
```

2024-10-01 15:15 UTC, ATaylorAerospace approved these changes

2024-10-12 20:45 UTC, johko requested changes
Thanks  so much for this amazing contribution and sorry it took me so long until I reviewed.

Actually I wanted to dig into the history of the YOLO models myself for a long time now and I think your overview does a great job in pointing out the most important parts.

As someone who still remembers the first YOLO release very well (and its slightly crazy creator), it has been a fun ride through the last 10 years to read this.

I mainly left formatting suggestions - but as always all suggestions are open for discussion, so please let me know if you have other thoughts on some of them.

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +required by deep networks to achieve multiple objectives.
```suggestion
* Concept of programmable gradient information (PGI) to cope with the various changes required by deep networks to achieve multiple objectives.
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +This short chapter presented the history/evolution of YOLO in a linear way. However, this is not the case—many other versions of YOLO were released in parallel. Notice the release of YOLOv4 and YOLOv
```suggestion
This short chapter presented the history/evolution of YOLO in a linear way. However, this is not the case — many other versions of YOLO were released in parallel. Notice the release of YOLOv4 and YOLOv5 in the same year. Other versions that we did not cover include YOLOvX (2021), which was based on YOLOv3 (2018), and YOLOR (2021), which was based on YOLOv4 (2020), and many others.
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion
```

2024-10-12 20:45 UTC, johko commented on chapters/en/_toctree.yml
> +  - title: YOLO; You only Look once
I would suggest to put all the first letters in capital here:
```suggestion
  - title: YOLO; You Only Look Once
```

2024-10-16 14:28 UTC, sezan92 commented on chapters/en/unit2/cnns/yolo.mdx
> +#### RCNN
```suggestion
#### R- CNN (Region-based Convolutional Neural Networks)
```

2024-10-16 14:29 UTC, sezan92 commented on chapters/en/unit2/cnns/yolo.mdx
> +Fast RCNN is focused on improvisation over the original RCNN. They added these three improvements
```suggestion
Fast RCNN is focused on improvisation over the original RCNN. They added these four improvements
```

2024-10-21 05:51 UTC, sezan92 commented on chapters/en/unit2/cnns/yolo.mdx
> +
```suggestion

The Faster R-CNN completely removes the need for the Selective Search algorithm! These features resulted in an improvement of the inference time by 90% compared to that of Fast R-CNN!!
```

2024-10-22 17:27 UTC, ATaylorAerospace approved these changes
LGTM

2024-10-23 18:01 UTC, johko approved these changes
Thanks for the changes, LGTM :+1:

2024-10-23 18:01 UTC, merged