Added video processing section (Unit 7 - Multimodal Based Video Model)
johko/computer-vision-course pull request #355
Opened 2024-10-05 05:54 UTC by 1kmmk1

Added  `multimodal-based-video-models.mdx` at video processing section. This document provides an overview of various multimodal video architectures which integrate different kinds of modalities into a unified representation space.  

Part of [Proposed Outline Revision for Unit 7. Video & Video Processing #348](https://github.com/johko/computer-vision-course/discussions/348)

## Who can review? (Initial)

@jungnerd @cjfghk5697 @1kmmk1 and anyone who wants to review!

2024-10-05 06:37 UTC, mreraser commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +<!-- Modality Overview Image -->
```suggestion
/* Modality Overview Image */
```
According to the [mdx syntax](https://learn.microsoft.com/en-us/sql/mdx/comments-mdx-syntax?view=sql-server-ver16), comments should be handled as follows.

2024-10-05 06:38 UTC, mreraser commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +<!-- VideoBERT Overview Image -->
```suggestion
/* VideoBERT Overview Image */
```

2024-10-05 06:38 UTC, mreraser commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +<!-- VATT Overview Image -->
```suggestion
/* VATT Overview Image */ 
```

2024-10-05 06:38 UTC, mreraser commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +<!-- ImageBind Overview Image -->
```suggestion
/* ImageBind Overview Image */
```

2024-10-05 06:44 UTC, mreraser commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +<U>Note</U>: If you're looking the detailed training process of MERLOT, make sure to reference the MERLOT paper as well as earlier works like [HERO](https://aclanthology.org/2020.emnlp-main.161.pdf),
```suggestion
<u>Note</u>: If you're looking the detailed training process of MERLOT, make sure to reference the MERLOT paper as well as earlier works like [HERO](https://aclanthology.org/2020.emnlp-main.161.pdf), [CBT](https://arxiv.org/pdf/1906.05743) and [HAMMER](https://aclanthology.org/2020.emnlp-main.161.pdf).
```
To use underline html tag, I think <u></u> is appropriate.

2024-10-05 06:44 UTC, mreraser commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +1. <U>Vision-language branch</U> for processing video frames
```suggestion
1. <u>Vision-language branch</u> for processing video frames 
```

2024-10-05 06:44 UTC, mreraser commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +2. <U>Audio-language branch</U> for handling audio signals.
```suggestion
2. <u>Audio-language branch</u> for handling audio signals. 
```

2024-10-05 07:08 UTC, mreraser commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +Videos encompasses a variety of modalities beyond just sequences of images. Understanding these different modalities is crucial for comprehensive video analysis and processing. The primary modalities
```suggestion
Videos encompass a variety of modalities beyond just sequences of images. Understanding these different modalities is crucial for comprehensive video analysis and processing. The primary modalities present in videos include:
```
The verb was changed to `encompass` because the subject(`videos`) is plural.

2024-10-05 07:11 UTC, mreraser commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +As time goes on, there is a growing body of research focused on integrating an wide range of modalities all at once.
```suggestion
As time goes on, there is a growing body of research focused on integrating a wide range of modalities all at once. 
```
Since "wide" starts with a consonant, "a wide" is the correct expression.

2024-10-05 08:49 UTC, 1kmmk1 commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +As time goes on, there is a growing body of research focused on integrating an wide range of modalities all at once.
Thank you the detailed review! I checked all your suggestions and commit them.

2024-10-26 20:15 UTC, johko requested changes
Thanks for the contribution and sorry for the late review.
It was a really nice read and I feel like I've got a better idea about multimodal video models now ;)

I mainly left formatting suggestions (mostly repetitive) and make sure to add the pictures :)

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +[MERLOT](https://arxiv.org/abs/2106.02636) is designed to improve multimodal reasoning by learning from large-scale video-text datasets. It focuses on understanding  interactions between visual and t
```suggestion
[MERLOT](https://arxiv.org/abs/2106.02636) is designed to improve multimodal reasoning by learning from large-scale video-text datasets. It focuses on understanding interactions between visual and textual information using no labeled data. By leveraging the large-scale unlabeled dataset **YT-Temporal-180M**,  **MERLOT** demonstrates strong performance in visual commonsense reasoning without relying on heavy visual supervision.
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +- **Key Features**
```suggestion
**Key Features**
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +2. Frame-Caption Matching Task(From [CBT](https://arxiv.org/pdf/1906.05743), [HAMMER](https://aclanthology.org/2020.emnlp-main.161.pdf))
```suggestion
1. Temporal Reordering Task (from [HERO](https://aclanthology.org/2020.emnlp-main.161.pdf))
2. Frame-Caption Matching Task (from [CBT](https://arxiv.org/pdf/1906.05743), [HAMMER](https://aclanthology.org/2020.emnlp-main.161.pdf))
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +- Why It Matters
```suggestion
Why It Matters
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +<u>Note</u>: If you're looking the detailed training process of MERLOT, make sure to reference the MERLOT paper as well as earlier works like [HERO](https://aclanthology.org/2020.emnlp-main.161.pdf),
I think there is at least one word missing, maybe like:
```suggestion
<u>Note</u>: If you're looking to understand the detailed training process of MERLOT, make sure to refer to the MERLOT paper as well as earlier works like [HERO](https://aclanthology.org/2020.emnlp-main.161.pdf), [CBT](https://arxiv.org/pdf/1906.05743) and [HAMMER](https://aclanthology.org/2020.emnlp-main.161.pdf).
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +- **Overview**
```suggestion
**Overview**
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +- **Key Features**
```suggestion
**Key Features**
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +2. Droptoken: Due to the redundancies in video(with audio, and text data), sampling only a subset of tokens allows for more efficient training.
```suggestion
2. Droptoken: Due to the redundancies in video (with audio and text data), sampling only a subset of tokens allows for more efficient training.
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +- **Why It Matter**
```suggestion
**Why It Matter**
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +- **Overview**
```suggestion
**Overview**
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +[Video-LLaMA](https://arxiv.org/abs/2306.02858) is a multimodal framework designed to extend Large Language Models (LLMs) to understand both visual and auditory content in videos. It integrates video
```suggestion
[Video-LLaMA](https://arxiv.org/abs/2306.02858) is a multimodal framework designed to extend Large Language Models (LLMs) to understand both visual and auditory content in videos. It integrates video, audio and text, allowing the model to process and generate meaningful responses grounded in audiovisual information. Video-LLaMA addresses two key challenges: capturing temporal changes in visual scenes and integrating audio-visual signals into a unified system.
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +- **Key Features**
```suggestion
**Key Features**
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +2. <u>Audio-language branch</u> for handling audio signals.
Looks better like this imo, but feel free to do as you like :slightly_smiling_face: 
```suggestion
1. <u>Vision-Language branch</u> for processing video frames 
2. <u>Audio-Language branch</u> for handling audio signals. 
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +- **Why It Matters**
```suggestion
**Why It Matters**
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +- **Overview**
```suggestion
**Overview**
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +/* ImageBind Overview Image */
Image ;)

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +ImageBind unifies many kinds of modalities by utilizing pairs of images and other modalities. By leveraging *InfoNCE* as the loss function, the model aligns representations between images and various
It feel a bit too repetitive, here is a little suggestion:
```suggestion
ImageBind unifies many kinds of modalities by utilizing pairs of images and other modalities. By leveraging *InfoNCE* as the loss function, the model aligns representations between the various inputs. Even in cases where paired data between non-image modalities are absent, ImageBind can effectively perform cross-modal retrieval and zero-shot tasks.
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +Additionally, the training process of ImageBind is relatively simpler compared to other models and can be implemented in various ways.
```suggestion
Additionally, the training process of ImageBind is relatively simple compared to other models and can be implemented in various ways.
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +- **Why It Matters**
```suggestion
**Why It Matters**
```

2024-10-26 20:15 UTC, johko commented on chapters/en/unit7/video-processing/multimodal-based-video-models.mdx
> +ImageBind's key contribution is its ability to integrate various modalities without the need for specific modality-paired datasets. Using images as a reference, it aligns and combines up to six diffe
```suggestion
ImageBind's key contribution is its ability to integrate various modalities without the need for specific modality-paired datasets. Using images as a reference, it aligns and combines up to six different modalities — such as audio, text, depth, and more — into a unified representation space. The significance lies in its capacity to achieve this alignment across multiple modalities simultaneously, without requiring direct pairing for each combination, making it highly efficient for multimodal learning.
```

2024-11-13 21:09 UTC, johko approved these changes
Thanks for the changes :slightly_smiling_face: 
Now it looks good to me :+1:

2024-11-14 10:48 UTC, ATaylorAerospace approved these changes
Great additions..LGTM!

2024-12-04 10:14 UTC, merged