Changed video processing section (Unit 7 - CNN Based Video Model)
johko/computer-vision-course pull request #356
Opened 2024-10-05 06:07 UTC by cjfghk5697

Changed`chapters/en/unit7/video-processing/overview-of-previous-sota-models.mdx` to `chapters/en/unit7/video-processing/cnn-based-video-model.mdx`  at video processing section. This document provides an overview of various CNN video architectures which integrate different kinds of modalities into a unified representation space.

Part of https://github.com/johko/computer-vision-course/discussions/348

Who can review? (Initial)
@jungnerd @cjfghk5697 @mreraser and anyone who wants to review!

2024-10-06 02:12 UTC, mreraser commented
Hello @cjfghk5697 😄  I think you haven't modified _toctree.yml file yet. 

```
RuntimeError: The following files are not present in the table of contents:
- unit7/video-processing/cnn-based-video-model
Add them to ../computer-vision-course/chapters/en/_toctree.yml.
```

2024-10-26 20:44 UTC, johko requested changes
Thank you for the contribution, was a pleasure to read and learn :slightly_smiling_face: 

I just left some smaller suggestions, mainly formatting related

2024-10-26 20:44 UTC, johko commented on chapters/en/_toctree.yml
> +  - title: Cnn Based Video Model
```suggestion
  - title: CNN Based Video Model
```

2024-10-26 20:44 UTC, johko commented on chapters/en/unit7/video-processing/cnn-based-video-model.mdx
> +# CNN Based Video Model
```suggestion
# CNN Based Video Models
```

2024-10-26 20:44 UTC, johko commented on chapters/en/unit7/video-processing/cnn-based-video-model.mdx
> +The success of Deep Learning, particularly CNNs trained on massive datasets like ImageNet, revolutionized image recognition. This trend continues in video processing. However, video data introduces a
```suggestion
The success of Deep Learning, particularly CNNs trained on massive datasets like ImageNet, revolutionized image recognition. This trend continues in video processing. However, video data introduces another dimension compared to static images: time. This simple change introduced a new set of challenges that CNNs trained in static images were not built to deal with.
```

2024-10-26 20:44 UTC, johko commented on chapters/en/unit7/video-processing/cnn-based-video-model.mdx
> +## Two-Stream Network(2014):
Mainly for consistency within the course, I would remove the colon in (sub)headlines
```suggestion
## Two-Stream Network(2014)
```

2024-10-26 20:44 UTC, johko commented on chapters/en/unit7/video-processing/cnn-based-video-model.mdx
> +## 3D ResNets(2017):
```suggestion
## 3D ResNets(2017)
```

2024-10-26 20:44 UTC, johko commented on chapters/en/unit7/video-processing/cnn-based-video-model.mdx
> +Standard 3D CNNs extend the concept to simultaneously capture spatial and temporal information using 3D kernels (2D spatial information + temporal information). A drawback of this model is that the l
```suggestion
Standard 3D CNNs extend the concept to simultaneously capture spatial and temporal information using 3D kernels (2D spatial information + temporal information). A drawback of this model is that the large number of parameters result in the training being more computationally intensive and hence slower than the 2D version. Therefore, the 3D version of the ConvNets typically has fewer layers than the deeper architectures of 2D CNNs.
```

2024-10-26 20:44 UTC, johko commented on chapters/en/unit7/video-processing/cnn-based-video-model.mdx
> +Experiments showed that the 3D ResNets (especially deeper ones like the ResNet-34) outperform models like the C3D, particularly on larger datasets. Pretrained models like Sports-1M C3D can help mitig
Here you mention `C3D` as if it is already known, maybe shortly introduce it or give a link to the paper?

2024-10-26 20:44 UTC, johko commented on chapters/en/unit7/video-processing/cnn-based-video-model.mdx
> +## (2+1)D ResNets(2017):
```suggestion
## (2+1)D ResNets(2017)
```

2024-10-26 20:44 UTC, johko commented on chapters/en/unit7/video-processing/cnn-based-video-model.mdx
> +The evolution of video analysis models has been fascinating to witness. These models were heavily influenced by other SOTA models. For example, Two-StreamNets was motivated by the  ConvNets and (2+1)
```suggestion
The evolution of video analysis models has been fascinating to witness. These models were heavily influenced by other SOTA models. For example, Two-StreamNets was motivated by the ConvNets and (2+1)D ResNets were inspired by the 3D ResNets. As the research progresses, one can expect even more advanced architectures and techniques to emerge in the future.
```

2024-10-30 06:13 UTC, cjfghk5697 commented on chapters/en/unit7/video-processing/cnn-based-video-model.mdx
> +Experiments showed that the 3D ResNets (especially deeper ones like the ResNet-34) outperform models like the C3D, particularly on larger datasets. Pretrained models like Sports-1M C3D can help mitig
Thank you for reviewing it! I’ve added C3D research paper's link.

2024-11-12 18:31 UTC, ATaylorAerospace approved these changes
LGTM

2024-11-13 21:10 UTC, johko approved these changes
Thanks for the fixes. LGTM :+1:

2024-11-13 21:11 UTC, merged