Initial Draft Outline for VGG19
johko/computer-vision-course pull request #57
Opened 2023-11-09 13:40 UTC by sezan92

This PR is a testing PR for initial VGG19. The writing had been done by albertkao227. The other members reviewed and we have opened our first PR to check if this process is fine.

2023-11-09 13:57 UTC, merveenoyan reviewed
Thanks a lot for this section, especially liked the comparison part :)

2023-11-09 13:57 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/README.md
> +Common Pretrained Models
This file should've been just `2.mdx` for our documentation builder. Please refer to README.md for guidelines.

2023-11-09 13:57 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +|Layer Type |Filter Size|Output Size|No. Params|
I think this is too in-depth.

2023-11-09 13:57 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +- Input is 224X224 image.
```suggestion
- Inputs are 224X224 images. 
```

2023-11-09 13:57 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +- 3X3 convolution kernels with 2X2 max pooling layers.
```suggestion
- Convolution kernel shape is (3,3) and max pooling window shape is (2,2).
```

2023-11-09 13:57 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +The VGG architecture was developed in 2014 by Karen Simonyan and Andrew Zisserman from the Visual Geometry Group at Oxford University. The authors detailed key advancements in convolutional neural ne
Maybe have a less technical/academic introduction at first, i.e. general to specific, e.g. [this chapter on encoder models](https://huggingface.co/learn/nlp-course/en/chapter1/5?fw=pt#encoder-models). 
The beginning of the paragraph can be something like: VGG is one of the earliest pre-trained models with convolutions.

2023-11-09 13:57 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +2. VGG Network Architechture
Headers should be looking like this
```suggestion
## VGG Network Architechture 
```

2023-11-09 13:57 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +3. Key Comparisons
Very nice section :)

2023-11-09 13:58 UTC, merveenoyan commented
I'd like @MKhalusova to give a review to get an earlier sense of tone of the course.

2023-11-09 14:45 UTC, lunarflu requested changes
Good start! Keeping commits short and fast like this is perfect 🚀

2023-11-09 14:45 UTC, lunarflu commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +The VGG architecture was developed in 2014 by Karen Simonyan and Andrew Zisserman from the Visual Geometry Group at Oxford University. The authors detailed key advancements in convolutional neural ne
Like Merve mentions, I think we could condense this into just the juciest / most exciting bits! An alternative (personal preference) could be like:

"Following its development in 2014, VGG significantly improved [50%, some easy statistic etc] over [previous options] with increased depth and convolutional filters. What makes these new additions so important is...." -> (then maybe you could expand a bit, 1-3 precise ways it helps)

2023-11-09 14:45 UTC, lunarflu commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +- VGG (16 or 19 layers) is relatively deeper than other SOTA networks at the time. AlexNet, winning model for ILSVRC 2012 only has 8 layers.
`AlexNet, the winning model`

2023-11-09 14:45 UTC, lunarflu commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +- VGG (16 or 19 layers) is relatively deeper than other SOTA networks at the time. AlexNet, winning model for ILSVRC 2012 only has 8 layers.
`was relatively deeper`

2023-11-09 14:46 UTC, MKhalusova reviewed
This page heavily assumes that the reader has some knowledge from the previous chapter ("2.1 Convolutional Neural Networks/2.1.1 General Architecture Overview/"). It assumes that the reader understands what a convolution kernel is, are max-pooling layers, etc.  We'll need to double-check that this is actually the case to avoid confusion. Ideally, in the previous section, we would talk about all these parts of a CNN, and this would be a good place to give a concrete example and explain some whys and hows. Here are some questions that a reader may have. Why did we choose this model as one of the examples? What is so special about it? What is the ImageNet Large Scale Visual Recognition Challenge (ILSVRC)? What tasks would one use this model for? (And maybe in what cases it wouldn't be the best choice)
You touch on some of this at the end, in the list, but it may be easier to learn if there was a less academic and more engaging, explainer style. You can find some examples of a more approachable style in the recent audio course, e.g. [CTC architectures](https://huggingface.co/learn/audio-course/chapter3/ctc) page.

2023-11-10 05:38 UTC, sezan92 commented
thank you @lunarflu @MKhalusova @merveenoyan for the review. I will address them within 2-3 days God willing. hopefully that is fine.

2023-11-13 08:03 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +|Layer Type |Filter Size|Output Size|No. Params|
@merveenoyan sorry, i am confused, should i update this section?

2023-11-13 08:07 UTC, sezan92 commented
> It assumes that the reader understands what a convolution kernel is, are max-pooling layers, etc. We'll need to double-check that this is actually the case to avoid confusion

@MKhalusova I understand this point . I think the best way is to discuss with the contributors of the previous chapter. I have not seen their outline, I will ping them in discord.

> Here are some questions that a reader may have. Why did we choose this model as one of the examples? What is so special about it? What is the ImageNet Large Scale Visual Recognition Challenge (ILSVRC)? What tasks would one use this model for? (And maybe in what cases it wouldn't be the best choice)

these are good questions. But I think they need a separate `markdown` files for details. Don't you think theses questions deserve a separate PR? if yes, may be we can address them in another PR.

2023-11-13 08:08 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +- VGG (16 or 19 layers) is relatively deeper than other SOTA networks at the time. AlexNet, winning model for ILSVRC 2012 only has 8 layers.
updated in https://github.com/johko/computer-vision-course/pull/57/commits/b68fbac69251dabefbb6478295d4bce1b0ca74fb

2023-11-13 08:08 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +- VGG (16 or 19 layers) is relatively deeper than other SOTA networks at the time. AlexNet, winning model for ILSVRC 2012 only has 8 layers.
updated in https://github.com/johko/computer-vision-course/pull/57/commits/b68fbac69251dabefbb6478295d4bce1b0ca74fb

2023-11-13 08:08 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +The VGG architecture was developed in 2014 by Karen Simonyan and Andrew Zisserman from the Visual Geometry Group at Oxford University. The authors detailed key advancements in convolutional neural ne
@lunarflu @merveenoyan i tried to make it less technical in https://github.com/johko/computer-vision-course/pull/57/commits/b68fbac69251dabefbb6478295d4bce1b0ca74fb

2023-11-13 15:40 UTC, MKhalusova commented
@sezan92 Why do you think that there's a need for a separate file to answer these questions? From my perspective, this file is a great place to address them.

2023-11-14 03:30 UTC, sezan92 commented
> Why do you think that there's a need for a separate file to answer these questions? From my perspective, this file is a great place to address them.

@MKhalusova I think the reason is that all of the models mentioned in this chapter are trying to solve the challenge. So the details of this discussion are related to all of the models. That is why I think it deserves another `mdx` file so that we can refer to the details of the Imagenet challenge from other models' descriptions.

2023-11-17 09:28 UTC, lunarflu reviewed
Thanks for improving this! Looks a lot more condensed now

2023-11-17 09:29 UTC, lunarflu approved these changes

2023-11-20 16:22 UTC, merveenoyan reviewed
Thanks a lot for iterating on this! Overall looks good

2023-11-20 16:22 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +1. Introduction
```suggestion
## Introduction
```

2023-11-20 16:22 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +The VGG architecture was developed in 2014 by Karen Simonyan and Andrew Zisserman from the Visual Geometry Group -and hence named VGG- at Oxford University. The model demonstrated significant improve
```suggestion
The VGG architecture was developed in 2014 by Karen Simonyan and Andrew Zisserman from the Visual Geometry Group -and hence named VGG- at Oxford University. The model demonstrated significant improvements over the past models at that time, to be specific, 2014 ImageNet challenge also known as ILSVRC.
```

2023-11-20 16:22 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +|Layer Type |Filter Size|Output Size|No. Params|
Maybe you could remove the architecture table itself, that's what I meant

2023-11-20 16:22 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +3. Key Comparisons
```suggestion
## Key Comparisons 
```

2023-11-20 16:22 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +4. Pytorch Example
```suggestion
## PyTorch Example
```

2023-11-20 16:22 UTC, merveenoyan commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg19.py
> +import torch.nn as nn
I have only one comment: can you make the file naming format similar to the course here? https://github.com/huggingface/course/tree/main/chapters/en

2023-11-24 08:24 UTC, michaelshekasta commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/2.mdx
> +1. VGG19
Should we write about AlexNet?

2023-11-24 08:25 UTC, michaelshekasta commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +The VGG architecture was developed in 2014 by Karen Simonyan and Andrew Zisserman from the Visual Geometry Group -and hence named VGG- at Oxford University. The model demonstrated significant improve
I think that we should write something about ImageNet Challenge (the task, the dataset size, etc)

2023-11-24 08:27 UTC, michaelshekasta commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +|Linear|N/A|1000|4,096,000|
Do you think that we should add a graph or illustration?
e.g. https://neurohive.io/wp-content/uploads/2018/11/vgg16-1-e1542731207177.png

2023-11-29 14:38 UTC, sezan92 commented
@merveenoyan @michaelshekasta sorry for late , i will address the comments this week iA

2023-11-29 18:18 UTC, lunarflu commented
Thanks @sezan92 ! 🤗 ❤️ Always let us know if there is any confusion or if there's a part you get stuck on.

I think we are close to merging after a few more fixes which will be great! 🚀

2023-12-02 15:03 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +|Linear|N/A|1000|4,096,000|
@michaelshekasta we plan to add illustration in a new PR. can you resolve it for now?

2023-12-02 15:09 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg19.py
> +import torch.nn as nn
@merveenoyan I have updated in https://github.com/johko/computer-vision-course/pull/57/commits/e9808fcb023e8618801384a70d5a1868068c4b78

2023-12-02 15:10 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/0.mdx
> +1. Introduction
```suggestion
## Introduction
```

2023-12-02 15:14 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/2.mdx
> +1. VGG19
in #39 we agreed not to add details about Alexnet due to it being a bit old

2023-12-02 15:15 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/vgg.md
> +The VGG architecture was developed in 2014 by Karen Simonyan and Andrew Zisserman from the Visual Geometry Group -and hence named VGG- at Oxford University. The model demonstrated significant improve
@michaelshekasta as I mentioned in https://github.com/johko/computer-vision-course/pull/57#issuecomment-1809489260 , I think it is better to have a separate page for Imagenet Challenge as all the CNN models will eventually refer to that informations.

2023-12-04 16:39 UTC, MKhalusova approved these changes
Looks good to me, thank you for polishing the doc! 
One thought - would it make sense to add a link to a pre-trained VGG19 checkpoint - e.g. https://huggingface.co/timm/vgg19.tv_in1k ?

2023-12-05 21:07 UTC, merveenoyan approved these changes
Looks good to me, only thing is renaming the file name without 2.1 and so on like: 
```
.
└── course/
    └── chapters/
        ├── chapter0/
        │   ├── introduction.mdx
        │   └── getting_started.mdx
        ├── chapter1/
        │   └── ...mdx
        └── _toctree.yml
```
and we can merge :) 
In fact it should be under: `chapters/en/Unit 2 - Convolutional Neural Networks`

2023-12-06 17:42 UTC, AI-ANK reviewed
Great work on the content! I've added just a few suggestions to polish it further,

2023-12-06 17:42 UTC, AI-ANK commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/0.mdx
> +        return x
**Duplication of VGG19 class definition**
Found a small issue in the PyTorch example section: The `VGG19` class definition is duplicated. Could you please remove the second one?

2023-12-06 17:42 UTC, AI-ANK commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/0.mdx
> +## VGG Network Architechture
I recommend adding a visual representation of the VGG Network Architecture to enhance understanding. A clear diagram can effectively convey the structure and progression of layers. I found a useful open-source visual on Papers with Code, which could be a great addition. 
[Visual Representation of VGG Network Architecture](https://paperswithcode.com/method/vgg)

2023-12-06 17:42 UTC, AI-ANK commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/0.mdx
> +class VGG19(nn.Module):
This is well-structured. Just a good to have suggestion - to enhance understanding for learners, the following additional details could be included in the comments:

ReLU Activation: `nn.ReLU(), # ReLU activation function introduces non-linearity, helping the network learn complex patterns.`

Max Pooling Rationale: `# Max pooling with a 2x2 kernel and stride of 2 to reduce spatial dimensions and increase computational efficiency.`

Convolutional Layers Progression: `# Increasing the number of filters in deeper layers to 128, then 256, and finally 512. This allows the network to capture more complex features as we go deeper.`

Dropout Layer Explanation: `# Dropout layer with a probability of 0.5 to prevent overfitting by randomly dropping units during training, which forces the network to learn redundant representations.`

2023-12-07 03:42 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/0.mdx
> +## VGG Network Architechture
@AI-ANK we will add the visual representation in another PR

2023-12-07 03:43 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/0.mdx
> +class VGG19(nn.Module):
@AI-ANK from other review comments we sensed that these are very deep details. I think they can be left not added. what do you say ? @merveenoyan @lunarflu

2023-12-07 03:45 UTC, sezan92 commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/0.mdx
> +        return x
```suggestion
```

2023-12-07 15:26 UTC, merveenoyan commented
Hey @sezan92 after you change the path of this file we can merge, content wise it's nice!

2023-12-08 06:40 UTC, AI-ANK commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/0.mdx
> +## VGG Network Architechture
Great! That makes sense.

2023-12-08 06:40 UTC, AI-ANK commented on course/2 Neural Network Architectures/2.1 Convolutional Neural Networks/2.1.2 Common Pre-Trained Models/0.mdx
> +class VGG19(nn.Module):
Yup, makes sense

2023-12-11 04:40 UTC, sezan92 commented
> Hey @sezan92 after you change the path of this file we can merge, content wise it's nice!

@merveenoyan sorry for late reply, I had to take some break. I am back. I am updating

2023-12-11 04:45 UTC, sezan92 commented
@merveenoyan @AI-ANK @MKhalusova sorry, i think we can merge this PR when approved.

2023-12-11 17:38 UTC, MKhalusova approved these changes
LGTM, feel free to merge with enough approvals.

2023-12-12 11:16 UTC, johko approved these changes
LGTM

2023-12-12 11:17 UTC, merged